pmd and build fix for R2_1
hmcts/sptribs-case-api pull request #1072
Opened 2023-06-27 11:43 UTC by ATedy

### Change description ###

Enter a description.

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SPTRIBS-

**Before merging a pull request make sure that:**

- [ ] tests have been updated / new tests has been added (if needed)
- [ ] README and other documentation has been updated / added (if needed)

**If this ticket will have any visible impact on users and is not behind a feature toggle, make sure that:**
- [ ] this ticket been reviewed by QA
- [ ] the user story been signed off by the PO

Note that bug fixes, dependency updates and technical tasks do not directly impact the user experience and can be merged without QA and PO review.

### If this user story cannot be immediately merged find a way to put it behind a feature toggle and get it merged.

2023-06-27 13:06 UTC, osheaf01 commented on config/owasp/suppressions.xml
> +      <cve>CVE-2023-35116</cve>
This should already be there, pull the latest and you won't need to add this

2023-06-27 13:07 UTC, osheaf01 requested changes
Just one change needed - don't duplicate the suppression
Otherwise LGTM

2023-06-27 13:28 UTC, ATedy commented on config/owasp/suppressions.xml
> +      <cve>CVE-2023-35116</cve>
I have pulled the latest from R2.1 but I don't see this specific supression

2023-06-28 09:53 UTC, ElifDenizEsea approved these changes

2023-06-28 09:58 UTC, osheaf01 commented on config/owasp/suppressions.xml
> +      <cve>CVE-2023-35116</cve>
Sorry, it's a 2.0. change. Resolving.

2023-06-28 11:30 UTC, osheaf01 approved these changes
LGTM

2023-06-29 10:38 UTC, merged