St 670 build problems new
hmcts/sptribs-case-api pull request #125
Opened 2022-10-10 21:27 UTC by geciciserkan

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-10-11 08:10 UTC, muradalamv1 approved these changes

2022-10-11 08:25 UTC, sjamihmcts approved these changes

2022-10-11 08:30 UTC, spotstory requested changes
Just in case, can we disable our deployment to AAT for the time being - I don't think we should risk an AAT deployment with the Jurisdiction still set to DIVORCE

2022-10-11 10:43 UTC, osheaf01 commented on src/functionalTest/java/uk/gov/hmcts/sptribs/testutil/DocumentManagementStore.java
> +            serviceAuthenticationGenerator.generate("nfdiv_case_api"),
Does this need to be "nfdiv_case_api"? 
Extract out as a property?

2022-10-11 10:44 UTC, osheaf01 submitted a review, later dismissed
LGTM, just one question inline

2022-10-11 11:12 UTC, muradalamv1 approved these changes

2022-10-21 08:52 UTC, muradalamv1 approved these changes

2022-10-21 08:56 UTC, jaberelfasi approved these changes

2022-10-21 08:58 UTC, geciciserkan commented
> Just in case, can we disable our deployment to AAT for the time being - I don't think we should risk an AAT deployment with the Jurisdiction still set to DIVORCE

2022-10-21 09:00 UTC, spotstory approved these changes

2022-10-21 09:00 UTC, merged