ST- Removing client secret.
hmcts/sptribs-case-api pull request #1463
Opened 2023-11-10 13:38 UTC by osheaf01

### Change description ###

Enter a description.

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SPTRIBS-

**Before merging a pull request make sure that:**

- [ ] tests have been updated / new tests has been added (if needed)
- [ ] README and other documentation has been updated / added (if needed)

**If this ticket will have any visible impact on users and is not behind a feature toggle, make sure that:**
- [ ] this ticket been reviewed by QA
- [ ] the user story been signed off by the PO

Note that bug fixes, dependency updates and technical tasks do not directly impact the user experience and can be merged without QA and PO review.

### If this user story cannot be immediately merged find a way to put it behind a feature toggle and get it merged.

2023-11-10 15:28 UTC, tomxelliott commented on src/main/resources/application.yaml
> -    secret: ${IDAM_CLIENT_SECRET:thUphEveC2Ekuqedaneh4jEcRuba4t2t}
Only the secret itself needs to be removed, not the config entry

2023-11-10 15:28 UTC, tomxelliott commented on src/main/resources/application.yaml
> -    secret: ${IDAM_CLIENT_SECRET:thUphEveC2Ekuqedaneh4jEcRuba4t2t}
Please erase commit history after merge so this secret is no longer visible in git history

2023-11-10 15:29 UTC, tomxelliott requested changes
Only the secret itself needs to be removed, not the config entry

2023-11-10 15:37 UTC, tomxelliott commented on src/main/resources/application.yaml
> -    secret: ${IDAM_CLIENT_SECRET:thUphEveC2Ekuqedaneh4jEcRuba4t2t}
`secret: ${IDAM_CLIENT_SECRET:DUMMY_SECRET} `

2024-01-22 16:08 UTC, colmlynch60 approved these changes
LGTM

2024-01-23 14:33 UTC, closed without merging