St 492
hmcts/sptribs-case-api pull request #16
Opened 2022-08-10 10:29 UTC by osheaf01

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/ST-492

### Change description ###

Project path refactored from "divorce" to "sptribs". Associated import reordering to comply with checkstyle.

Fixed a typo from "Prefrence" to "Preference" while doing this change.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-08-11 13:07 UTC, spotstory requested changes
package.json has some unintended changes by the looks of it

2022-08-11 13:42 UTC, osheaf01 commented
Backslash changes reversed.

2022-08-12 09:24 UTC, spotstory submitted a review, later dismissed

2022-08-12 10:30 UTC, spotstory approved these changes

2022-08-12 11:03 UTC, jaberelfasi approved these changes

2022-08-12 16:56 UTC, spotstory approved these changes

2022-08-15 14:51 UTC, jaberelfasi approved these changes

2022-08-15 14:53 UTC, muradalamv1 approved these changes

2022-08-15 15:01 UTC, merged