Removed Comments and added Test.
hmcts/sptribs-case-api pull request #1639
Opened 2024-01-09 10:33 UTC by Jefex7

### Change description ###

Audit Unit Tests in Case API - Exception, IDAM, JudicialRefData Modules

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DTSSTCI-119

2024-01-11 11:04 UTC, rajaram-nagarajan requested changes

2024-01-11 11:04 UTC, rajaram-nagarajan commented on src/test/java/uk/gov/hmcts/sptribs/judicialrefdata/JudicialServiceTest.java
> -        //Given
We make sure all the null and empty values are handled properly in JudicialService and IdamService by adding specific test cases to JudicialServiceTest and IdamServiceTest files. And also make sure all the flow are covered at least by one test case.

2024-01-11 11:11 UTC, rajaram-nagarajan commented on src/test/java/uk/gov/hmcts/sptribs/judicialrefdata/JudicialServiceTest.java
> -        //When
Also if there is a chance to improve the respective code file, do not hesitate to fix it. (For example, var data type can be replaced by the respective data types in JudicialService etc etc)

2024-01-16 17:21 UTC, oleon23 approved these changes

2024-01-17 13:27 UTC, gmmagruder approved these changes

2024-01-18 10:47 UTC, oleon23 approved these changes

2024-01-22 14:31 UTC, JakeCG submitted a review, later dismissed

2024-01-22 14:50 UTC, tomxelliott submitted a review, later dismissed

2024-01-25 12:55 UTC, rajaram-nagarajan requested changes

2024-01-25 12:55 UTC, rajaram-nagarajan commented on src/test/java/uk/gov/hmcts/sptribs/exception/DocumentUploadOrDeleteExceptionTest.java
> +
In general, all the cleanup like removing unwanted lines and formatting and removing warnings can be done for all the files.

2024-01-25 12:55 UTC, rajaram-nagarajan commented on src/test/java/uk/gov/hmcts/sptribs/exception/DocumentUploadOrDeleteExceptionTest.java
>              documentManagementController.deleteDocument(CASE_TEST_AUTHORIZATION, documentInfo.getDocumentId());
As per the method, uploadDocument controller needs to be called instead of deleteDocument.

2024-01-25 12:55 UTC, rajaram-nagarajan commented on src/test/java/uk/gov/hmcts/sptribs/exception/CaseCreateOrUpdateExceptionTest.java
>              caseManagementService.createCase(updateCaseTestAuth, caseData);
As per the method, updateCase needs to be used instead of createCase.

2024-01-25 12:55 UTC, rajaram-nagarajan commented on src/test/java/uk/gov/hmcts/sptribs/exception/CaseCreateOrUpdateExceptionTest.java
>      @Test
word 'test' can be removed all the test method names.

2024-01-25 12:55 UTC, rajaram-nagarajan commented on src/test/java/uk/gov/hmcts/sptribs/exception/CaseCreateOrUpdateExceptionTest.java
> +        assertTrue(exception.getMessage().contains(CASE_UPDATE_FAILURE_MSG));
A new test can be added for fetchCaseDetails as well.

2024-01-25 12:55 UTC, rajaram-nagarajan commented on src/test/java/uk/gov/hmcts/sptribs/exception/InvalidResourceExceptionTest.java
>  class InvalidResourceExceptionTest {
@Serial annotation can be added to all the Exception classes for variable serialVersionUID

2024-01-25 12:55 UTC, rajaram-nagarajan commented on src/test/java/uk/gov/hmcts/sptribs/exception/InvalidResourceExceptionTest.java
> +    void testInvalidResourceExceptionThrownForNonExistentFile() throws RuntimeException {
The unwanted/unused Exception methods can be removed from Exception class InvalidResourceException.

2024-01-25 12:55 UTC, rajaram-nagarajan commented on src/test/java/uk/gov/hmcts/sptribs/idam/IdamServiceTest.java
>          ReflectionTestUtils.setField(idamService, "systemUpdateUserName", TEST_SYSTEM_UPDATE_USER_EMAIL);
File - JudicialService.java
1. Mark all the private class variables as file
2. Move all the public methods to the top of the class and all private methods to the bottom of the class.

2024-01-26 10:45 UTC, rajaram-nagarajan approved these changes
LGTM

2024-01-29 11:48 UTC, tomxelliott approved these changes

2024-01-29 11:50 UTC, merged