Changed the case category and sub category to dropdown.(ST-492)
hmcts/sptribs-case-api pull request #23
Opened 2022-08-16 15:26 UTC by muradalamv1

[### JIRA link (if applicable) ###](https://tools.hmcts.net/jira/browse/ST-332)

Changed the case category and sub category to dropdown

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-08-17 10:29 UTC, osheaf01 commented on src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseDocumentsCIC.java
> +        final List<ListValue<T>> list = isEmpty(documents) ? new ArrayList<>() : new ArrayList<>(documents);
Very minor quibble, but maybe call what's in the list ListItem rather than ListValue?

2022-08-17 10:42 UTC, osheaf01 commented on src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseDocumentsCIC.java
> +
Why create a new ArrayList from documents, which is final, add your item and return it?

Why not make documents non-final, and just do documents.add(listValue)?
Is there a reason it needs to be the 0th element?

2022-08-17 11:05 UTC, muradalamv1 commented
yes there is a reason because case worker can add multiple documents and can be shown as a separate document with number shown on the documents  and can be removed separate. also we followed the nf div structure which was instructed to us.. but we can also discuss this and find alternative if you think we can improve it.

________________________________
From: osheaf01 ***@***.***>
Sent: 17 August 2022 11:42
To: hmcts/sptribs-case-api ***@***.***>
Cc: Murad Alam ***@***.***>; Author ***@***.***>
Subject: Re: [hmcts/sptribs-case-api] Changed the case category and sub category to dropdown.(ST-492) (PR #23)

CAUTION: This email originated from outside of Version 1. Do not click links or open attachments unless you recognise the sender and know the content is safe.


@osheaf01 commented on this pull request.

________________________________

In src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseDocumentsCIC.java<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhmcts%2Fsptribs-case-api%2Fpull%2F23%23discussion_r947771894&data=05%7C01%7Cmurad.alam%40version1.com%7Cd0841389e8644e942ff508da803d36ec%7C3e0088dc06294ae6aa8c813e7a296f50%7C0%7C0%7C637963297652486967%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7GmNuPAIYQ%2F1Y5Ttzpk0ZzsBQJVuBkhyLieGyH49llo%3D&reserved=0>:

> +        access = {DefaultAccess.class}
+    )
+    private List<ListValue<CICDocument>> applicantDocumentsUploaded;
+
+
+    public static <T> List<ListValue<T>> addDocumentToTop(final List<ListValue<T>> documents, final T value) {
+        return addDocumentToTop(documents, value, null);
+    }
+
+    public static <T> List<ListValue<T>> addDocumentToTop(final List<ListValue<T>> documents, final T value, final String id) {
+        final var listItemId = isBlank(id) ? String.valueOf(randomUUID()) : id;
+        final var listValue = new ListValue<T>(listItemId, value);
+        final List<ListValue<T>> list = isEmpty(documents) ? new ArrayList<>() : new ArrayList<>(documents);
+
+        list.add(0, listValue);
+


Why create a new ArrayList from documents, which is final, add your item and return it?

Why not make documents non-final, and just do documents.add(listValue)?
Is there a reason it needs to be the 0th element?

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhmcts%2Fsptribs-case-api%2Fpull%2F23%23pullrequestreview-1075494574&data=05%7C01%7Cmurad.alam%40version1.com%7Cd0841389e8644e942ff508da803d36ec%7C3e0088dc06294ae6aa8c813e7a296f50%7C0%7C0%7C637963297652486967%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GnlKfY0a1SLQzsW3xsjGfzSvwTm3zSHiTtd7uC%2Fdhnc%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZW5KSI37S7BBU64CNUEZ6TVZS62DANCNFSM56WIU2NQ&data=05%7C01%7Cmurad.alam%40version1.com%7Cd0841389e8644e942ff508da803d36ec%7C3e0088dc06294ae6aa8c813e7a296f50%7C0%7C0%7C637963297652486967%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KPv7FDACo05TqsCDla82tlzFc2qmLjjjNRGVDM7v9mo%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>


Classification: Controlled

2022-08-17 11:09 UTC, osheaf01 commented on src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseDocumentsCIC.java
> +            sortedDocuments.forEach(
If you're adding previousDocuments to the end of the list, just use addAll without the index of 1?
"Magic numbers" are a code smell.

2022-08-17 11:10 UTC, osheaf01 commented on src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseDocumentsCIC.java
> +        final List<ListValue<T>> sortedDocuments = new ArrayList<>();
Does this have to be private? Could this method be of wider use?

2022-08-17 11:10 UTC, osheaf01 commented on src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
>      private ApplicantCICDetails applicantCICDetails;
Please reverse this, Prefrence is a typo

2022-08-17 11:13 UTC, osheaf01 requested changes
A few suggestions, but please don't reintroduce the Prefrence typo, so please change that back.

2022-08-26 08:53 UTC, osheaf01 commented on src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseDocumentsCIC.java
> +            sortedDocuments.forEach(
I thought this was removed?

2022-09-08 14:34 UTC, closed without merging