ST-964 Contact Preference Type Check
hmcts/sptribs-case-api pull request #314
Opened 2023-01-03 14:55 UTC by ElifDenizEsea

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/ST-964

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-01-03 16:21 UTC, osheaf01 commented on src/main/java/uk/gov/hmcts/sptribs/ciccase/model/ContactPreferenceType.java
> +        return POST.name().equalsIgnoreCase(this.name());
Enums are singleton pattern - wouldn't `return POST == this;` work just as well? == is superior when checking enum equality, as it caters for nulls.

2023-01-03 16:22 UTC, osheaf01 requested changes
LGTM, just one query about the equality check?

2023-01-03 18:02 UTC, osheaf01 commented on src/main/java/uk/gov/hmcts/sptribs/common/event/page/ApplicantDetails.java
> +            && null != data.getCicCase().getApplicantAddress()) {
.equals defers to ==, I believe, but == is null-safe and it also checks type compatibility at compile time.
I'd also put the entity you know exists on the LHS, so

`ContactPreferenceType.POST == data.getCicCase().getApplicantContatDetailsPreference()` ?

2023-01-03 18:03 UTC, osheaf01 commented on src/main/java/uk/gov/hmcts/sptribs/common/event/page/RepresentativeDetails.java
> +            && null != data.getCicCase().getRepresentativeAddress()) {
As for comment above.

2023-01-03 18:03 UTC, osheaf01 commented on src/main/java/uk/gov/hmcts/sptribs/common/event/page/SubjectDetails.java
> +            && null != data.getCicCase().getAddress()) {
Same as comment above.

2023-01-03 18:04 UTC, osheaf01 requested changes
Again LGTM, bar just one suggestion as to how to check enum equality.

2023-01-03 18:05 UTC, osheaf01 commented on src/main/java/uk/gov/hmcts/sptribs/ciccase/model/ContactPreferenceType.java
>          return EMAIL.name().equalsIgnoreCase(this.name());
This has the same problems as the isPost() method originally proposed - could we fix this as part of this change?
Or else raise a tech debt ticket...

2023-01-03 20:28 UTC, muradalamv1 approved these changes

2023-01-04 09:52 UTC, osheaf01 approved these changes
LGTM

2023-01-04 09:55 UTC, merged