ST-606 Stay the case conformation page
hmcts/sptribs-case-api pull request #54
Opened 2022-09-12 16:21 UTC by ElifDenizEsea

**Before creating a pull request make sure that:**

- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/ST-606

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-09-12 16:27 UTC, spotstory submitted a review, later dismissed

2022-09-12 16:58 UTC, pavihmcts submitted a review, later dismissed

2022-09-13 10:04 UTC, pavihmcts submitted a review, later dismissed

2022-09-13 10:21 UTC, spotstory requested changes
COURT_ADMIN_CIC is duplicated in caseworkersstaythecase.java

2022-09-13 11:48 UTC, spotstory approved these changes

2022-09-13 11:49 UTC, pavihmcts approved these changes

2022-09-13 12:22 UTC, ElifDenizEsea commented
merged

2022-09-13 12:23 UTC, merged