Feat/st 1388
hmcts/sptribs-case-api pull request #991
Opened 2023-06-04 15:12 UTC by ElifDenizEsea

### Change description ###

bundling issues

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/ST-1388

**Before merging a pull request make sure that:**

- [ ] tests have been updated / new tests has been added (if needed)
- [ ] README and other documentation has been updated / added (if needed)

**If this ticket will have any visible impact on users and is not behind a feature toggle, make sure that:**
- [ ] this ticket been reviewed by QA
- [ ] the user story been signed off by the PO

Note that bug fixes, dependency updates and technical tasks do not directly impact the user experience and can be merged without QA and PO review.

### If this user story cannot be immediately merged find a way to put it behind a feature toggle and get it merged.

2023-06-07 17:02 UTC, osheaf01 commented on src/main/java/uk/gov/hmcts/sptribs/document/bundling/client/BundlingService.java
> +                .id(null != objectLinkedHashMap.get("id") ? objectLinkedHashMap.get("id").toString() : "")
Can you make "description", "id", "title" etc local static String variables?

2023-06-07 17:04 UTC, osheaf01 requested changes
Just some minor comments on BundlingService.

Lots of changes here, presume you're bringing 2.1 up to the same level as 2?

2023-06-08 13:11 UTC, osheaf01 approved these changes
LGTM

2023-06-08 14:17 UTC, sjamihmcts approved these changes

2023-06-08 14:36 UTC, merged